### ISSUE TITLE
Fix inability to make the app as default on some devices

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Dialer#530]
more info at https://www.reddit.com/r/SimpleMobileTools/comments/10k34wi/issue_choose_default_dialer_app/

**Comment by warriormaster12** [comment]
Can confirm that this issue happens on redmi note 11 pro, miui 13 android 12

**Comment by al1ce23** [comment]
Is this a bug in MIUI13? Simple-Dialer is my default app for dialing but when trying to call someone it still always asks which dialer i want to use.

**Comment by tibbi** [comment]
should be fixed in 6.18.0

**Comment by warriormaster12** [comment]
@tibbi I'm on 5.18 and I still get the dialogue in miui 13

**Comment by tibbi** [comment]
do you have the app set as the default for handling calls? Try reinstalling it and granting everything that is asked

**Comment by warriormaster12** [comment]
Noticed that I was running an older version, installed the new one from github releases, set the dialer as the default, I still get the dialogue.

**Comment by tibbi** [comment]
what are the steps for reproducing it? You click on a contact in Simple Dialers Recents tab and it shows an app picker?

**Comment by warriormaster12** [comment]
Open application, select a person you want to call from contacts list, tap contact's phone number, dialogue pops up

**Comment by tibbi** [comment]
you mean clicking on a contact at the first Contacts tab? That just opens contact details, it is another app triggering the call.

**Comment by warriormaster12** [comment]
Oh okay so I tried to call from call history and it didn't popup. Still, it is really annoying that it happens from contacts since I call from there.

**Comment by tibbi** [comment]
but from Simple Contacts Pro or which app?

**Comment by warriormaster12** [comment]
Oh okay so I tried to call from call history and it didn't popup. Still, it is really annoying that it happens from contacts since I call from there.

**Comment by tibbi** [comment]
that is handled by your system though, it is unrelated to us
