### ISSUE TITLE
Call screen stays in application tray after call is ended

### ISSUE THREAD

**Issue by smasty** [SimpleMobileTools/Simple-Dialer#61]
Sometimes, the call screen stays in the activity tray, even after the call is ended. (see screenshot 1) I was able to observe this happening in the following situations:

1. For an incoming call, it doesn't matter who ends the call, the call screen stays in the activity tray.
2. For an outgoing call, if the caller (me, using this app) ends the call, it is reverted back to the main Dialer screen. So this works fine.
3. For an outgoing call, if the other side ends the call, the call screen will stay in the activity tray. Moreover in this case, the background color of the app icon in the activity tray does not respect my setting and instead always shows the default orange background (see screenshot 2, compare with screenshot 1). This might be caused by the launcher though, I'm not sure. However, I never experienced a wrong color in the activity tray using any other SMT application.

Simple Dialer version 5.3.0 from FDroid, "vanilla" Android 10 on a Pixel 3a

Screenshot 1: _Call screen stays in the activity tray after the call was ended_
![image](https://user-images.githubusercontent.com/218524/84567537-aa6ade80-ad79-11ea-9e1a-88ac126581e4.png)

Screenshot 2: _Notice the default orange icon in this case (case number 3) compared to the color in screenshot 1_
![image](https://user-images.githubusercontent.com/218524/84567553-cbcbca80-ad79-11ea-9c1d-69f75acae7b9.png)

**Comment by teemue** [comment]
Can confirm this happens on Nokia 5.1 as well. Android 9.

**Comment by MarcinWieczorek** [comment]
Confirmed, mate 10 lite

**Comment by tibbi** [comment]
should be fixed in 5.6.1 already

**Comment by MarcinWieczorek** [comment]
When dialing but canceled the call
![scrot_20210113_112851](https://user-images.githubusercontent.com/3466984/104440384-921ea480-5592-11eb-8522-71a1bccbcf36.png)
Does this count as a variation of this issue?

**Comment by tibbi** [comment]
sure

**Comment by MarcinWieczorek** [comment]
The issue still exists, it stays even after a successful call.

**Comment by tibbi** [comment]
make sure you unstuck the old bug first by swiping the app away from recents

**Comment by MarcinWieczorek** [comment]
I'm quite sure I did that a few times today. I'll keep you updated
